### ISSUE TITLE
Install of osqp-0.6.2.post0.tar.gz fails due to qdldl

### ISSUE THREAD

**Issue by Mahalakshmivignesh** [osqp/osqp#740]
I am trying to install osqp-0.6.2.post0.tar.gz. But it fails with below error while building wheels for qdldlCollecting osqp==0.6.2.post0
 ```
 Downloading osqp-0.6.2.post0.tar.gz (219 kB)
     |████████████████████████████████| 219 kB 2.6 MB/s            
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /tmp/pip-standalone-pip-sdshqk5x/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-qzl2c9ck/normal --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- qdldl
       cwd: None
  Complete output (137 lines):
  WARNING: The directory '/var/lib/mysql/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
  Collecting qdldl
    Downloading qdldl-0.1.7.post5.tar.gz (73 kB)
    Installing build dependencies: started
    Installing build dependencies: still running...
    Installing build dependencies: still running...
    Installing build dependencies: still running...
    Installing build dependencies: still running...
    Installing build dependencies: still running...
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
    Preparing metadata (pyproject.toml): started
    Preparing metadata (pyproject.toml): finished with status 'done'
  Collecting scipy>=0.13.2
    Downloading scipy-1.13.1.tar.gz (57.2 MB)
    Installing build dependencies: started
    Installing build dependencies: still running...
    Installing build dependencies: still running...
    Installing build dependencies: still running...
    Installing build dependencies: still running...
    Installing build dependencies: still running...
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
    Installing backend dependencies: started
    Installing backend dependencies: finished with status 'done'
    Preparing metadata (pyproject.toml): started
    Preparing metadata (pyproject.toml): still running...
    Preparing metadata (pyproject.toml): still running...
    Preparing metadata (pyproject.toml): still running...
    Preparing metadata (pyproject.toml): still running...
    Preparing metadata (pyproject.toml): still running...
    Preparing metadata (pyproject.toml): still running...
    Preparing metadata (pyproject.toml): still running...
    Preparing metadata (pyproject.toml): still running...
    Preparing metadata (pyproject.toml): still running...
    Preparing metadata (pyproject.toml): still running...
    Preparing metadata (pyproject.toml): still running...
    Preparing metadata (pyproject.toml): still running...
    Preparing metadata (pyproject.toml): still running...
    Preparing metadata (pyproject.toml): still running...
    Preparing metadata (pyproject.toml): still running...
    Preparing metadata (pyproject.toml): still running...
    Preparing metadata (pyproject.toml): still running...
    Preparing metadata (pyproject.toml): still running...
    Preparing metadata (pyproject.toml): still running...
    Preparing metadata (pyproject.toml): still running...
    Preparing metadata (pyproject.toml): still running...
    Preparing metadata (pyproject.toml): still running...
    Preparing metadata (pyproject.toml): still running...
    Preparing metadata (pyproject.toml): still running...
    Preparing metadata (pyproject.toml): still running...
    Preparing metadata (pyproject.toml): still running...
    Preparing metadata (pyproject.toml): still running...
    Preparing metadata (pyproject.toml): still running...
    Preparing metadata (pyproject.toml): finished with status 'done'
  Collecting numpy>=1.7
    Downloading numpy-2.0.2.tar.gz (18.9 MB)
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
    Installing backend dependencies: started
    Installing backend dependencies: finished with status 'done'
    Preparing metadata (pyproject.toml): started
    Preparing metadata (pyproject.toml): still running...
    Preparing metadata (pyproject.toml): still running...
    Preparing metadata (pyproject.toml): still running...
    Preparing metadata (pyproject.toml): finished with status 'done'
  Building wheels for collected packages: qdldl, numpy, scipy
    Building wheel for qdldl (pyproject.toml): started
    Building wheel for qdldl (pyproject.toml): finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 /tmp/tmp_u0s4emn_in_process.py build_wheel /tmp/tmp3d4ei1qd
         cwd: /tmp/pip-install-d3cv9qub/qdldl_41549c6051b24fbba0d7a28fe65bbd1c
    Complete output (47 lines):
    running bdist_wheel
    running build
    running build_ext
    CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
      Compatibility with CMake < 3.10 will be removed from a future version of
      CMake.
  
      Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
      to tell CMake that the project requires at least <min> but has been updated
      to work with policies introduced by <max> or earlier.
  
  
    -- The C compiler identification is GNU 11.5.0
    -- The CXX compiler identification is GNU 11.5.0
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Check for working C compiler: /usr/bin/cc - skipped
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Check for working CXX compiler: /usr/bin/c++ - skipped
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    CMake Error at qdldl/CMakeLists.txt:2 (cmake_minimum_required):
      Compatibility with CMake < 3.5 has been removed from CMake.
  
      Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
      to tell CMake that the project requires at least <min> but has been updated
      to work with policies introduced by <max> or earlier.
  
      Or, add -DCMAKE_POLICY_VERSION_MINIMUM=3.5 to try configuring anyway.
  
  
    -- Configuring incomplete, errors occurred!
    gmake: Makefile: No such file or directory
    gmake: *** No rule to make target 'Makefile'.  Stop.
    building 'qdldl' extension
    creating build/temp.linux-s390x-cpython-39/cpp
    g++ -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -march=z14 -mtune=z15 -fasynchronous-unwind-tables -fstack-clash-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -march=z14 -mtune=z15 -fasynchronous-unwind-tables -fstack-clash-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -march=z14 -mtune=z15 -fasynchronous-unwind-tables -fstack-clash-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -Ic -Ic/qdldl/include -I/tmp/pip-build-env-f69rx3m_/overlay/lib/python3.9/site-packages/pybind11/include -I/tmp/pip-build-env-f69rx3m_/overlay/lib/python3.9/site-packages/pybind11/include -I/usr/include/python3.9 -c cpp/qdldl.cpp -o build/temp.linux-s390x-cpython-39/cpp/qdldl.o -O3 -std=c++11
    In file included from cpp/qdldl.hpp:2,
                     from cpp/qdldl.cpp:1:
    c/qdldl/include/qdldl.h:5:10: fatal error: qdldl_types.h: No such file or directory
        5 | #include "qdldl_types.h"
          |          ^~~~~~~~~~~~~~~
    compilation terminated.
    error: command '/usr/bin/g++' failed with exit code 1
    ----------------------------------------
    ERROR: Failed building wheel for qdldl
    Building wheel for numpy (pyproject.toml): started
    Building wheel for numpy (pyproject.toml): finished with status 'done'
    Created wheel for numpy: filename=numpy-2.0.2-cp39-cp39-linux_s390x.whl size=6867672 sha256=4419e332c0c26c825f376faa1e0c24585b0306395d5696c9cf4d525301003931
    Stored in directory: /tmp/pip-ephem-wheel-cache-yovuo8r7/wheels/21/e8/64/8174e3d1007bb14455a2a60139d6566202565cebf6d3bff70f
    Building wheel for scipy (pyproject.toml): started
    Building wheel for scipy (pyproject.toml): finished with status 'done'
    Created wheel for scipy: filename=scipy-1.13.1-cp39-cp39-linux_s390x.whl size=26872951 sha256=616c4a5d2456595b6d2e188948ea7a441157cfdb0cafee8233245e45c6ea9002
    Stored in directory: /tmp/pip-ephem-wheel-cache-yovuo8r7/wheels/f9/1e/b4/6062892a30d1259c141ddde498176288fcc25078ae4faa7311
  Successfully built numpy scipy
  Failed to build qdldl
  ERROR: Could not build wheels for qdldl, which is required to install pyproject.toml-based projects
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/c0/90/4cf48c200a89e46bcad87e12469ee36fc03d0c3f16b703b747e8c4bf618e/osqp-0.6.2.post0.tar.gz#sha256=5f0695f26a3bef0fae91254bc283fab790dcca0064bfe0f425167f9c9e8b4cbc (from https://pypi.org/simple/osqp/). Command errored out with exit status 1: /usr/bin/python3 /tmp/pip-standalone-pip-sdshqk5x/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-qzl2c9ck/normal --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- qdldl Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement osqp==0.6.2.post0 (from versions: 0.0.0, 0.1.3, 0.2.0, 0.2.1, 0.3.0, 0.4.0, 0.4.1, 0.5.0, 0.6.0, 0.6.1, 0.6.2, 0.6.2.post0, 0.6.2.post4, 0.6.2.post5, 0.6.2.post8, 0.6.2.post9, 0.6.3, 0.6.4, 0.6.5, 0.6.6, 0.6.7, 0.6.7.post0, 0.6.7.post1, 0.6.7.post2, 0.6.7.post3, 1.0.0b1, 1.0.0b3, 1.0.0b4, 1.0.0, 1.0.1, 1.0.2, 1.0.3)
ERROR: No matching distribution found for osqp==0.6.2.post0
bash-5.1# python --version

```
cmake version available - cmake-4.0.0. 
Errors:
```
1.     gmake: Makefile: No such file or directory
    gmake: *** No rule to make target 'Makefile'.  Stop.
2.  c/qdldl/include/qdldl.h:5:10: fatal error: qdldl_types.h: No such file or directory
3. ERROR: No matching distribution found for osqp==0.6.2.post0
```
For the error 3, though the 0.6.2.post0 version is available, it says no matching distribution. I am looking into that. But need to see the reason for other two errors.

**Comment by imciner2** [comment]
Please either downgrade your cmake version to a 3.x version or update to OSQP 1.0. The CMake compatibility in qdldl was fixed in OSQP 1.0.

**Comment by Mahalakshmivignesh** [comment]
I have uninstalled the other versions and had 3.31.6 for cmake & 1.0 for OSQP. But i am still getting same error. 
```
bash-5.1# pip install cmake==3.31.6
WARNING: The directory '/var/lib/mysql/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
Collecting cmake==3.31.6
  Downloading cmake-3.31.6-py3-none-manylinux_2_17_s390x.manylinux2014_s390x.whl (26.9 MB)
     |████████████████████████████████| 26.9 MB 6.3 MB/s            
Installing collected packages: cmake
Successfully installed cmake-3.31.6
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
bash-5.1# pip install qdldl==0.1.7.post5
WARNING: The directory '/var/lib/mysql/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
Collecting qdldl==0.1.7.post5
  Downloading qdldl-0.1.7.post5.tar.gz (73 kB)
     |████████████████████████████████| 73 kB 9.4 MB/s            
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: scipy>=0.13.2 in /usr/local/lib64/python3.9/site-packages (from qdldl==0.1.7.post5) (1.13.1)
Requirement already satisfied: numpy>=1.7 in /usr/local/lib64/python3.9/site-packages (from qdldl==0.1.7.post5) (1.24.2)
Building wheels for collected packages: qdldl
  Building wheel for qdldl (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /usr/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmp9geszclo
       cwd: /tmp/pip-install-hl_lxlzk/qdldl_ea5e0cc046664222aa539979c2c7b284
  Complete output (47 lines):
  running bdist_wheel
  running build
  running build_ext
  CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
    Compatibility with CMake < 3.10 will be removed from a future version of
    CMake.
  
    Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
    to tell CMake that the project requires at least <min> but has been updated
    to work with policies introduced by <max> or earlier.
  
  
  -- The C compiler identification is GNU 11.5.0
  -- The CXX compiler identification is GNU 11.5.0
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /usr/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  CMake Error at qdldl/CMakeLists.txt:2 (cmake_minimum_required):
    Compatibility with CMake < 3.5 has been removed from CMake.
  
    Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
    to tell CMake that the project requires at least <min> but has been updated
    to work with policies introduced by <max> or earlier.
  
    Or, add -DCMAKE_POLICY_VERSION_MINIMUM=3.5 to try configuring anyway.
  
  
  -- Configuring incomplete, errors occurred!
  gmake: Makefile: No such file or directory
  gmake: *** No rule to make target 'Makefile'.  Stop.
  building 'qdldl' extension
  creating build/temp.linux-s390x-cpython-39/cpp
  g++ -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -march=z14 -mtune=z15 -fasynchronous-unwind-tables -fstack-clash-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -march=z14 -mtune=z15 -fasynchronous-unwind-tables -fstack-clash-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -march=z14 -mtune=z15 -fasynchronous-unwind-tables -fstack-clash-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -Ic -Ic/qdldl/include -I/tmp/pip-build-env-r24q3wui/overlay/lib/python3.9/site-packages/pybind11/include -I/tmp/pip-build-env-r24q3wui/overlay/lib/python3.9/site-packages/pybind11/include -I/usr/include/python3.9 -c cpp/qdldl.cpp -o build/temp.linux-s390x-cpython-39/cpp/qdldl.o -O3 -std=c++11
  In file included from cpp/qdldl.hpp:2,
                   from cpp/qdldl.cpp:1:
  c/qdldl/include/qdldl.h:5:10: fatal error: qdldl_types.h: No such file or directory
      5 | #include "qdldl_types.h"
        |          ^~~~~~~~~~~~~~~
  compilation terminated.
  error: command '/usr/bin/g++' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for qdldl
Failed to build qdldl
ERROR: Could not build wheels for qdldl, which is required to install pyproject.toml-based projects
instead: https://pip.pypa.io/warnings/venv
bash-5.1# pip list installed
WARNING: The directory '/var/lib/mysql/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
Package              Version
-------------------- --------
chardet              4.0.0
cmake                3.31.6
dbus-python          1.2.18
decorator            4.4.2
distro               1.5.0
ecos                 2.0.14
gpg                  1.15.1
idna                 2.10
iniparse             0.4
Jinja2               3.1.6
joblib               1.4.2
libcomps             0.1.18
MarkupSafe           3.0.2
numpy                1.24.2
osqp                 1.0.3
pip                  21.3.1
PyGObject            3.40.1
pyinotify            0.9.6
PySocks              1.7.1
python-dateutil      2.8.1
requests             2.25.1
rpm                  4.16.1.3
scipy                1.13.1
selinux              3.6
sepolicy             3.6
setools              4.4.4
setuptools           53.0.0
six                  1.15.0
subscription-manager 1.29.42
systemd-python       234
urllib3              1.26.5
```
Any suggestion?

**Comment by Mahalakshmivignesh** [comment]
i am doing it for s390x arch. Are the changes available for that?

**Comment by cjerdonek** [comment]
> Please either downgrade your cmake version to a 3.x version or update to OSQP 1.0. The CMake compatibility in qdldl was fixed in OSQP 1.0.

Does QDLDL 0.1.8 need to be published to PyPI as well, though? This comment of yours says the issue was fixed in QDLDL 0.1.8 and OSQP 1.0:
https://github.com/osqp/qdldl/issues/60#issuecomment-2767445014
@Mahalakshmivignesh's logs above show that it's trying to install `qdldl==0.1.7.post5` (since 0.1.8 isn't available on PyPI).

**Comment by Mahalakshmivignesh** [comment]
https://pypi.org/project/qdldl/0.1.7.post5/#files - the source files in this also has `cmake_minimum_required (VERSION 3.5)`. This means the 0.1.7 already has min version as 3.5, rit?
